name: CD

on:
  push:
    branches:
      - main
      - test/cicd

  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Build and deploy web
    runs-on: ubuntu-latest
    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1

      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18.x

      # 安装 pnpm
      - name: Install pnpm
        run: npm install pnpm -g

      # 缓存pnpm依赖
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      # 安装项目依赖
      - name: Install Dependencies
        run: pnpm install

      # 构建程序
      - name: Build Website
        run: pnpm run build

      # 部署到服务器
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER_FRONTEND }}
          password: ${{ secrets.FTP_PASS_FRONTEND }}
          local-dir: ${{ github.workspace }}/dist/
          server-dir: ./


  backend:
    name: Build and deploy service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/service
    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1

      # 检查工作目录
      - name: Check workspace
        run: pwd

      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18.x

      # 安装 pnpm
      - name: Install pnpm
        run: npm install pnpm -g

      # 缓存pnpm依赖
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      # 安装项目依赖
      - name: Install Dependencies
        run: pnpm install

      # 构建程序
      - name: Build Website
        run: pnpm run build

      # 部署到服务器
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER_BACKEND }}
          password: ${{ secrets.FTP_PASS_BACKEND }}
          local-dir: ${{ github.workspace }}/service/build/
          server-dir: ./build/

      # 启动后端服务
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            #!/usr/bin/env bash
            eval "$(vfox activate bash)"
            vfox use nodejs@22.13.0
            cd ${{ secrets.BACKEND_PATH }}/build/ 
            pwd
            (pm2 restart chatgpt-web-service || pm2 start "pnpm prod" --name "chatgpt-web-service")

  # 并行运行任务
  deploy:
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    steps:
      - name: Notify deployment complete
        run: echo "Deployment completed!"