name: CD

on:
  push:
    branches:
      - main
      - test/cicd

  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Build and deploy web
    runs-on: ubuntu-latest
    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1

      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18.x

      # 安装 pnpm
      - name: Install pnpm
        run: npm install pnpm -g

      # 缓存pnpm依赖
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      # 安装项目依赖
      - name: Install Dependencies
        run: pnpm install

      # 构建程序
      - name: Build Website
        run: pnpm run build

      # 切换目录
      - name: Change to dist directory
        run: cd dist

      # 部署到服务器
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ./*
          target: ${{ secrets.FRONTEND_PATH }}

  backend:
    name: Build and deploy service
    runs-on: ubuntu-latest
    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1

      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18.x

      # 安装 pnpm
      - name: Install pnpm
        run: npm install pnpm -g

      # 切换目录
      - name: Change to dist directory
        run: cd service

      # 缓存pnpm依赖
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      # 安装项目依赖
      - name: Install Dependencies
        run: pnpm install

      # 构建程序
      - name: Build Website
        run: pnpm run build

      # 切换目录
      - name: Change to dist directory
        run: cd dist

      # 部署到服务器
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ./*
          target: ${{ secrets.BACKEND_PATH }}

      # 启动后端服务
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.BACKEND_PATH }}
            vfox use nodejs@22.13.0
            pnpm prod

  # 并行运行任务
  deploy:
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    steps:
      - name: Notify deployment complete
        run: echo "Deployment completed!"